# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
   
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: setup dependencies
      shell: powershell
      run: |
        Get-Date -Format G
        $Env:Path += ";C:\msys64\usr\bin"
        cd ${{github.workspace}}
        mkdir deps
        Get-Date -Format G
        wget http://apps.jcns.fz-juelich.de/redmine/attachments/download/350/local_x64.zip -O ${{runner.temp}}\local_x64.zip
        Get-Date -Format G
        7z x ${{runner.temp}}\local_x64.zip -odeps
        Get-Date -Format G
        dir deps
        dir deps/local_x64
        
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools
        python -m pip install numpy matplotlib
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
        dir: '${{ github.workspace }}/qt5/'
        install-deps: 'true'
        modules: 'qtcharts qtwebengine'
        mirror: 'http://mirrors.ocf.berkeley.edu/qt/'
        cached: 'false'
        
    # use ccache for building BornAgain, might save time
    - name: Prepare ccache timestamp
      id: ccache_cache_timestamp
      shell: cmake -P {0}
      run: |
        string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
        message("::set-output name=timestamp::${current_date}")
        
    - name: ccache cache files for BornAgain
      uses: actions/cache@v1.1.0
      with:
        path: .ccache
        key: bornagain-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
        restore-keys: |
          bornagain-ccache-
          
    - name: Build BornAgain
      shell: cmd
      env:
        CCACHE_DIR: $GITHUB_WORKSPACE/.ccache
        CCACHE_COMPRESS: "true"
        CCACHE_COMPRESSLEVEL: "6"
        CCACHE_MAXSIZE: "1000M"
      run: |
        set OPTLIBS=${{github.workspace}}\deps\local_x64
        set QTDIR=${{github.workspace}}\qt5\Qt\5.14.2\msvc2017_64
        set PATH=%OPTLIBS%\lib;%QTDIR%\bin;%PATH%
        echo %OPTLIBS%
        echo %QTDIR%
        echo %PATH%
        cd ${{github.workspace}}
        git clone --recursive https://github.com/gpospelov/BornAgain.git
        cd BornAgain
        git checkout TrWinBuild
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_INCLUDE_PATH=%OPTLIBS%/include -DCMAKE_LIBRARY_PATH=%OPTLIBS%/lib -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache ..
        cmake --build . --config Release -j4
        
    - name: Run functional tests
      shell: cmd
      run: |
        echo %QTDIR%
        echo %OPTLIBS%
        set OPTLIBS=${{github.workspace}}\deps\local_x64
        set PATH=%OPTLIBS%\lib;%QTDIR%\bin;%PATH%
        echo %PATH%
        cd ${{github.workspace}}\BornAgain\build
        ctest -LE Fullcheck --output-on-failure

    - name: Functional test output
      if: failure()
      shell: cmd
      run: |
        cd ${{github.workspace}}\BornAgain\build
        type Testing\Temporary\LastTest.log

